//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartG.Resources.idioma {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class mainMessageBox {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal mainMessageBox() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SmartG.Resources.idioma.mainMessageBox", typeof(mainMessageBox).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocurrió un error al generar el Cover, favor de contactar al soporte técnico.
        /// </summary>
        internal static string Emision_Documentos1 {
            get {
                return ResourceManager.GetString("Emision_Documentos1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocurrió un error inesperado al generar el documento (nota Reaseguro), favor de contactar al soporte técnico para futura referencia.
        /// </summary>
        internal static string Emision_Documentos10 {
            get {
                return ResourceManager.GetString("Emision_Documentos10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archivo generado satisfactoriamente, ¿Deseas abrir la carpeta?.
        /// </summary>
        internal static string Emision_Documentos11 {
            get {
                return ResourceManager.GetString("Emision_Documentos11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocurrió un error al generar el Schedule, favor de contactar al soporte técnico.
        /// </summary>
        internal static string Emision_Documentos2 {
            get {
                return ResourceManager.GetString("Emision_Documentos2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocurrió un error al generar la nota de reaseguro, favor de contactar al soporte técnico.
        /// </summary>
        internal static string Emision_Documentos3 {
            get {
                return ResourceManager.GetString("Emision_Documentos3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocurrió un error al generar el wording, favor de contactar al soporte técnico.
        /// </summary>
        internal static string Emision_Documentos4 {
            get {
                return ResourceManager.GetString("Emision_Documentos4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al combinar los documentos en una póliza, favor de contactar al soporte técnico.
        /// </summary>
        internal static string Emision_Documentos5 {
            get {
                return ResourceManager.GetString("Emision_Documentos5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Esta función concluirá el registro y generará los documentos finales, se recomienda generar un previo de la póliza para su revisión ya que una vez finalizado el registro no se podrá cambiar, si aun así deseas continuar con la conclusión del proceso has click en Si.
        /// </summary>
        internal static string Emision_Documentos6 {
            get {
                return ResourceManager.GetString("Emision_Documentos6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocurrió un error inesperado al generar el documento (cover), favor de contactar al soporte técnico para futura referencia.
        /// </summary>
        internal static string Emision_Documentos7 {
            get {
                return ResourceManager.GetString("Emision_Documentos7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocurrió un error inesperado al generar el documento (schedule), favor de contactar al soporte técnico para futura referencia.
        /// </summary>
        internal static string Emision_Documentos8 {
            get {
                return ResourceManager.GetString("Emision_Documentos8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocurrió un error inesperado al generar el documento (wording), favor de contactar al soporte técnico para futura referencia.
        /// </summary>
        internal static string Emision_Documentos9 {
            get {
                return ResourceManager.GetString("Emision_Documentos9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La poliza MX es necesaria para generar un registro nuevo o actualizar uno existente.
        /// </summary>
        internal static string Emision_Validacion1 {
            get {
                return ResourceManager.GetString("Emision_Validacion1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debes seleccionar solo una cobertura.
        /// </summary>
        internal static string Emision_Validacion10 {
            get {
                return ResourceManager.GetString("Emision_Validacion10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Deseas sustituir los valores por los que están actualmente en la sección Coberturas?.
        /// </summary>
        internal static string Emision_Validacion11 {
            get {
                return ResourceManager.GetString("Emision_Validacion11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Deseas sustituir los valores por defecto?.
        /// </summary>
        internal static string Emision_Validacion12 {
            get {
                return ResourceManager.GetString("Emision_Validacion12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Esta operación cambiara todo los valores ingresados en el formato, desea continuar?.
        /// </summary>
        internal static string Emision_Validacion13 {
            get {
                return ResourceManager.GetString("Emision_Validacion13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debes asignar un asegurado adicional para generar el título de la póliza en Genius.
        /// </summary>
        internal static string Emision_Validacion14 {
            get {
                return ResourceManager.GetString("Emision_Validacion14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No puedes eliminar al coasegurador XL Seguros.
        /// </summary>
        internal static string Emision_Validacion15 {
            get {
                return ResourceManager.GetString("Emision_Validacion15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No puedes eliminar al reasegurador XL Seguros.
        /// </summary>
        internal static string Emision_Validacion16 {
            get {
                return ResourceManager.GetString("Emision_Validacion16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Deseas guardar tus cambios antes de salir?.
        /// </summary>
        internal static string Emision_Validacion17 {
            get {
                return ResourceManager.GetString("Emision_Validacion17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Para utilizar esta función es necesario validar los datos de la póliza, ¿deseas continuar?.
        /// </summary>
        internal static string Emision_Validacion18 {
            get {
                return ResourceManager.GetString("Emision_Validacion18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Todos los campos deben de ser ingresados correctamente, da click en el botón &apos;Validar Registro&apos; para conocer qué falta..
        /// </summary>
        internal static string Emision_Validacion19 {
            get {
                return ResourceManager.GetString("Emision_Validacion19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error en longitud, debe contener 15 caracteres.
        /// </summary>
        internal static string Emision_Validacion2 {
            get {
                return ResourceManager.GetString("Emision_Validacion2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Para utilizar esta función es necesario validar los datos de la póliza, ¿deseas continuar?.
        /// </summary>
        internal static string Emision_Validacion20 {
            get {
                return ResourceManager.GetString("Emision_Validacion20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocurrió un error, no se encuentra el coasegurador XL México en la tabla Coaseguros, favor de verificarlo y agregarlo manualmente en caso de haber sido borrado.
        /// </summary>
        internal static string Emision_Validacion21 {
            get {
                return ResourceManager.GetString("Emision_Validacion21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error en seccion 1.
        /// </summary>
        internal static string Emision_Validacion3 {
            get {
                return ResourceManager.GetString("Emision_Validacion3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error en Seccion 2.
        /// </summary>
        internal static string Emision_Validacion4 {
            get {
                return ResourceManager.GetString("Emision_Validacion4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error en Seccion 3.
        /// </summary>
        internal static string Emision_Validacion5 {
            get {
                return ResourceManager.GetString("Emision_Validacion5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error en Seccion 4.
        /// </summary>
        internal static string Emision_Validacion6 {
            get {
                return ResourceManager.GetString("Emision_Validacion6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error en seccion 5.
        /// </summary>
        internal static string Emision_Validacion7 {
            get {
                return ResourceManager.GetString("Emision_Validacion7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: ya existe una póliza con ese folio, no puedes continuar sin un número de póliza exclusivo.
        /// </summary>
        internal static string Emision_Validacion8 {
            get {
                return ResourceManager.GetString("Emision_Validacion8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debes seleccionar una cobertura.
        /// </summary>
        internal static string Emision_Validacion9 {
            get {
                return ResourceManager.GetString("Emision_Validacion9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upps, parece que algo ha salido mal. Ayudanos a llenar un formulario de reporte de este error para ayudate a correguirlo cuanto antes. Gracias!.
        /// </summary>
        internal static string UnhandlerErrorMessage {
            get {
                return ResourceManager.GetString("UnhandlerErrorMessage", resourceCulture);
            }
        }
    }
}
