//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartG.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class FinkokErrores {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FinkokErrores() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SmartG.Resources.FinkokErrores", typeof(FinkokErrores).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se recibió la respuesta de la petición de forma exitosa.
        /// </summary>
        internal static string c1000 {
            get {
                return ResourceManager.GetString("c1000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No existen peticiones de cancelación en espera de respuesta para el uuid.
        /// </summary>
        internal static string c1001 {
            get {
                return ResourceManager.GetString("c1001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ya se recibió una respuesta para la petición de cancelación del uuid.
        /// </summary>
        internal static string c1002 {
            get {
                return ResourceManager.GetString("c1002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sello No Corresponde al RFC Receptor.
        /// </summary>
        internal static string c1003 {
            get {
                return ResourceManager.GetString("c1003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Existen más de una petición de cancelación para el mismo uuid.
        /// </summary>
        internal static string c1004 {
            get {
                return ResourceManager.GetString("c1004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El uuid es nulo no posee el formato correcto.
        /// </summary>
        internal static string c1005 {
            get {
                return ResourceManager.GetString("c1005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se rebaso el número máximo de solicitudes permitidas.
        /// </summary>
        internal static string c1006 {
            get {
                return ResourceManager.GetString("c1006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UUID Cancelado.
        /// </summary>
        internal static string c1201 {
            get {
                return ResourceManager.GetString("c1201", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UUID Previamente cancelado.
        /// </summary>
        internal static string c1202 {
            get {
                return ResourceManager.GetString("c1202", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UUID a cancelar no corresponde con el emisor.
        /// </summary>
        internal static string c1203 {
            get {
                return ResourceManager.GetString("c1203", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UUID No existe.
        /// </summary>
        internal static string c1205 {
            get {
                return ResourceManager.GetString("c1205", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estructura de folios no válida.
        /// </summary>
        internal static string c1302 {
            get {
                return ResourceManager.GetString("c1302", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Certificado no corresponde al emisor.
        /// </summary>
        internal static string c1305 {
            get {
                return ResourceManager.GetString("c1305", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Certificado no vigente.
        /// </summary>
        internal static string c1306 {
            get {
                return ResourceManager.GetString("c1306", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El certificado no es de tipo CSD.
        /// </summary>
        internal static string c1307 {
            get {
                return ResourceManager.GetString("c1307", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Certificado revocado o caduco.
        /// </summary>
        internal static string c1308 {
            get {
                return ResourceManager.GetString("c1308", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Petición de cancelación realizada exitosamente.
        /// </summary>
        internal static string c201 {
            get {
                return ResourceManager.GetString("c201", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Petición de cancelación realizada Previamente.
        /// </summary>
        internal static string c202 {
            get {
                return ResourceManager.GetString("c202", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No corresponde el RFC del Emisor y de quien solicita la cancelación.
        /// </summary>
        internal static string c203 {
            get {
                return ResourceManager.GetString("c203", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UUID No encontrado.
        /// </summary>
        internal static string c205 {
            get {
                return ResourceManager.GetString("c205", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuario y contraseña inválidos.
        /// </summary>
        internal static string c300 {
            get {
                return ResourceManager.GetString("c300", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XML Mal Formado.
        /// </summary>
        internal static string c301 {
            get {
                return ResourceManager.GetString("c301", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sello mal formado o inválido.
        /// </summary>
        internal static string c302 {
            get {
                return ResourceManager.GetString("c302", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sello no corresponde a emisor.
        /// </summary>
        internal static string c303 {
            get {
                return ResourceManager.GetString("c303", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Certificado Revocado o Caduco.
        /// </summary>
        internal static string c304 {
            get {
                return ResourceManager.GetString("c304", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La fecha de emisión no esta dentro de la vigencia del CSD del Emisor.
        /// </summary>
        internal static string c305 {
            get {
                return ResourceManager.GetString("c305", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El certificado no es de tipo CSD.
        /// </summary>
        internal static string c306 {
            get {
                return ResourceManager.GetString("c306", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comprobante timbrado previamente.
        /// </summary>
        internal static string c307 {
            get {
                return ResourceManager.GetString("c307", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Certificado no expedido por el SAT.
        /// </summary>
        internal static string c308 {
            get {
                return ResourceManager.GetString("c308", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patrón de Folio inválido.
        /// </summary>
        internal static string c309 {
            get {
                return ResourceManager.GetString("c309", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha y hora de generación fuera de rango.
        /// </summary>
        internal static string c401 {
            get {
                return ResourceManager.GetString("c401", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RFC del emisor no se encuentra en el régimen de contribuyentes.
        /// </summary>
        internal static string c402 {
            get {
                return ResourceManager.GetString("c402", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La fecha de emisión no es posterior al 01 de enero de 2012.
        /// </summary>
        internal static string c403 {
            get {
                return ResourceManager.GetString("c403", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autenticación no válida.
        /// </summary>
        internal static string c501 {
            get {
                return ResourceManager.GetString("c501", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El CFDI no contiene un timbre previo (método stamped).
        /// </summary>
        internal static string c603 {
            get {
                return ResourceManager.GetString("c603", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No ha registrado el RFC emisor bajo la cuenta de Finkok.
        /// </summary>
        internal static string c702 {
            get {
                return ResourceManager.GetString("c702", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cuenta suspendida.
        /// </summary>
        internal static string c703 {
            get {
                return ResourceManager.GetString("c703", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error con la contraseña de la llave Privada.
        /// </summary>
        internal static string c704 {
            get {
                return ResourceManager.GetString("c704", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XML estructura inválida.
        /// </summary>
        internal static string c705 {
            get {
                return ResourceManager.GetString("c705", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Socio Inválido.
        /// </summary>
        internal static string c706 {
            get {
                return ResourceManager.GetString("c706", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XML ya contiene un nodo TimbreFiscalDigital.
        /// </summary>
        internal static string c707 {
            get {
                return ResourceManager.GetString("c707", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se pudo conectar al SAT.
        /// </summary>
        internal static string c708 {
            get {
                return ResourceManager.GetString("c708", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error con el certificado al cancelar.
        /// </summary>
        internal static string c711 {
            get {
                return ResourceManager.GetString("c711", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El numero de &apos;noCertificado&apos; es diferente al del numero de certificado del atributo &apos;certificado&apos;.
        /// </summary>
        internal static string c712 {
            get {
                return ResourceManager.GetString("c712", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al crear XML de consulta Sector Primario.
        /// </summary>
        internal static string c715 {
            get {
                return ResourceManager.GetString("c715", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Firma Inválida - Consulta Sector Primario.
        /// </summary>
        internal static string c716 {
            get {
                return ResourceManager.GetString("c716", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al generar la firma del XML.
        /// </summary>
        internal static string c717 {
            get {
                return ResourceManager.GetString("c717", resourceCulture);
            }
        }
    }
}
