//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartG.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.0.1.0")]
    public class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Español")]
        public string idiomaSeleccionado {
            get {
                return ((string)(this["idiomaSeleccionado"]));
            }
            set {
                this["idiomaSeleccionado"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("+52 (55) 5953 7164")]
        public string TelefonoAtencion {
            get {
                return ((string)(this["TelefonoAtencion"]));
            }
            set {
                this["TelefonoAtencion"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("White")]
        public string ColorScheme {
            get {
                return ((string)(this["ColorScheme"]));
            }
            set {
                this["ColorScheme"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("admin")]
        public string usuarioDefault {
            get {
                return ((string)(this["usuarioDefault"]));
            }
            set {
                this["usuarioDefault"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://demo-facturacion.finkok.com/servicios/soap/stamp")]
        public string SmartG_FinkokTimbradoWS_StampSOAP {
            get {
                return ((string)(this["SmartG_FinkokTimbradoWS_StampSOAP"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://demo-facturacion.finkok.com/servicios/soap/cancel")]
        public string SmartG_FinkokCancelacionWS_CancelSOAP {
            get {
                return ((string)(this["SmartG_FinkokCancelacionWS_CancelSOAP"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=smartg_serverxl;Initial Catalog=DocumentosSmartG;Persist Security Inf" +
            "o=True;User ID=UsuarioXL;Password=kreios1020")]
        public string DocumentosSmartGConnectionString {
            get {
                return ((string)(this["DocumentosSmartGConnectionString"]));
            }
            set
            {
                this["DocumentosSmartGConnectionString"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://facturacion.finkok.com/servicios/soap/stamp")]
        public string SmartG_FinkokTimbradoWS_Produccion_StampSOAP {
            get {
                return ((string)(this["SmartG_FinkokTimbradoWS_Produccion_StampSOAP"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://facturacion.finkok.com/servicios/soap/cancel")]
        public string SmartG_FinkokCancelacionWS_Produccion_CancelSOAP {
            get {
                return ((string)(this["SmartG_FinkokCancelacionWS_Produccion_CancelSOAP"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://demo-facturacion.finkok.com/servicios/soap/retentions")]
        public string SmartG_FinkokRetencionesWS_Pruebas_RetentionsSOAP {
            get {
                return ((string)(this["SmartG_FinkokRetencionesWS_Pruebas_RetentionsSOAP"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://facturacion.finkok.com/servicios/soap/retentions")]
        public string SmartG_FinkokRetencionesWS_Produccion_RetentionsSOAP {
            get {
                return ((string)(this["SmartG_FinkokRetencionesWS_Produccion_RetentionsSOAP"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=smartg_serverxl;Initial Catalog=AxaXLProduccion;Persist Security Info" +
            "=True;User ID=usuarioXL;Password=kreios1020")]
        public string XLCatlinConnectionString {
            get {
                return ((string)(this["XLCatlinConnectionString"]));
            }
            set
            {
                this["XLCatlinConnectionString"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=smartg_serverxl;Initial Catalog=AxaXLClaims;Persist Security Info=Tru" +
            "e;User ID=usuarioXL;Password=kreios1020")]
        public string AxaXLClaimsConnectionString {
            get {
                return ((string)(this["AxaXLClaimsConnectionString"]));
            }
            set
            {
                this["AxaXLClaimsConnectionString"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("smart-g.support@kreios.mx")]
        public string emailSoporteTecnico {
            get {
                return ((string)(this["emailSoporteTecnico"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("120")]
        public int TiempoEsperaBloqueo {
            get {
                return ((int)(this["TiempoEsperaBloqueo"]));
            }
            set {
                this["TiempoEsperaBloqueo"] = value;
            }
        }
    }
}
