#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartG.BaseDatos
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="DocumentosSmartG")]
	public partial class DocumentsDBDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertDocumentosFacturacion(DocumentosFacturacion instance);
    partial void UpdateDocumentosFacturacion(DocumentosFacturacion instance);
    partial void DeleteDocumentosFacturacion(DocumentosFacturacion instance);
    #endregion
		
		public DocumentsDBDataContext() : 
				base(global::SmartG.Properties.Settings.Default.DocumentosSmartGConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DocumentsDBDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DocumentsDBDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DocumentsDBDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DocumentsDBDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<DocumentosFacturacion> DocumentosFacturacions
		{
			get
			{
				return this.GetTable<DocumentosFacturacion>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DocumentosFacturacion")]
	public partial class DocumentosFacturacion : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private System.Nullable<int> _Factura;
		
		private System.Data.Linq.Binary _Data;
		
		private string _Folio;
		
		private string _Serie;
		
		private string _NombreCliente;
		
		private string _RFC;
		
		private string _Poliza;
		
		private string _Usuario;
		
		private string _NombreDocumento;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnFacturaChanging(System.Nullable<int> value);
    partial void OnFacturaChanged();
    partial void OnDataChanging(System.Data.Linq.Binary value);
    partial void OnDataChanged();
    partial void OnFolioChanging(string value);
    partial void OnFolioChanged();
    partial void OnSerieChanging(string value);
    partial void OnSerieChanged();
    partial void OnNombreClienteChanging(string value);
    partial void OnNombreClienteChanged();
    partial void OnRFCChanging(string value);
    partial void OnRFCChanged();
    partial void OnPolizaChanging(string value);
    partial void OnPolizaChanged();
    partial void OnUsuarioChanging(string value);
    partial void OnUsuarioChanged();
    partial void OnNombreDocumentoChanging(string value);
    partial void OnNombreDocumentoChanged();
    #endregion
		
		public DocumentosFacturacion()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Factura", DbType="Int")]
		public System.Nullable<int> Factura
		{
			get
			{
				return this._Factura;
			}
			set
			{
				if ((this._Factura != value))
				{
					this.OnFacturaChanging(value);
					this.SendPropertyChanging();
					this._Factura = value;
					this.SendPropertyChanged("Factura");
					this.OnFacturaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Data", DbType="VarBinary(MAX)", UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary Data
		{
			get
			{
				return this._Data;
			}
			set
			{
				if ((this._Data != value))
				{
					this.OnDataChanging(value);
					this.SendPropertyChanging();
					this._Data = value;
					this.SendPropertyChanged("Data");
					this.OnDataChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Folio", DbType="VarChar(50)")]
		public string Folio
		{
			get
			{
				return this._Folio;
			}
			set
			{
				if ((this._Folio != value))
				{
					this.OnFolioChanging(value);
					this.SendPropertyChanging();
					this._Folio = value;
					this.SendPropertyChanged("Folio");
					this.OnFolioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Serie", DbType="VarChar(50)")]
		public string Serie
		{
			get
			{
				return this._Serie;
			}
			set
			{
				if ((this._Serie != value))
				{
					this.OnSerieChanging(value);
					this.SendPropertyChanging();
					this._Serie = value;
					this.SendPropertyChanged("Serie");
					this.OnSerieChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NombreCliente", DbType="VarChar(150)")]
		public string NombreCliente
		{
			get
			{
				return this._NombreCliente;
			}
			set
			{
				if ((this._NombreCliente != value))
				{
					this.OnNombreClienteChanging(value);
					this.SendPropertyChanging();
					this._NombreCliente = value;
					this.SendPropertyChanged("NombreCliente");
					this.OnNombreClienteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RFC", DbType="VarChar(50)")]
		public string RFC
		{
			get
			{
				return this._RFC;
			}
			set
			{
				if ((this._RFC != value))
				{
					this.OnRFCChanging(value);
					this.SendPropertyChanging();
					this._RFC = value;
					this.SendPropertyChanged("RFC");
					this.OnRFCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Poliza", DbType="VarChar(50)")]
		public string Poliza
		{
			get
			{
				return this._Poliza;
			}
			set
			{
				if ((this._Poliza != value))
				{
					this.OnPolizaChanging(value);
					this.SendPropertyChanging();
					this._Poliza = value;
					this.SendPropertyChanged("Poliza");
					this.OnPolizaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Usuario", DbType="VarChar(100)")]
		public string Usuario
		{
			get
			{
				return this._Usuario;
			}
			set
			{
				if ((this._Usuario != value))
				{
					this.OnUsuarioChanging(value);
					this.SendPropertyChanging();
					this._Usuario = value;
					this.SendPropertyChanged("Usuario");
					this.OnUsuarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NombreDocumento", DbType="VarChar(50)")]
		public string NombreDocumento
		{
			get
			{
				return this._NombreDocumento;
			}
			set
			{
				if ((this._NombreDocumento != value))
				{
					this.OnNombreDocumentoChanging(value);
					this.SendPropertyChanging();
					this._NombreDocumento = value;
					this.SendPropertyChanged("NombreDocumento");
					this.OnNombreDocumentoChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
